<?php

use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;
use Symfony\Component\Dotenv\Dotenv;

require __DIR__ . '/vendor/autoload.php';

$dotenv = new Dotenv();
try {
    $dotenv->load(__DIR__.'/.env');
} catch (Exception $exception) {
    error_log($exception->getMessage());
}

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://yandex.ru/drive/podpiska/saas/api/web/offers/create?offer_builder_type=long_term_offer_builder');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Authority: yandex.ru';
$headers[] = 'Pragma: no-cache';
$headers[] = 'Cache-Control: no-cache';
$headers[] = 'Lon: 37.611518';
$headers[] = 'Device-Memory: 8';
$headers[] = 'Saas: https://stable.carsharing.yandex.net';
$headers[] = 'Rtt: 150';
$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
$headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36';
$headers[] = 'Viewport-Width: 1920';
$headers[] = 'Lat: 55.750117';
$headers[] = 'Dpr: 1';
$headers[] = 'Downlink: 10';
$headers[] = 'Ect: 4g';
$headers[] = 'Lweb_appbuild: 1';
$headers[] = 'Sec-Ch-Ua: \"Chromium\";v=\"92\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"92\"';
$headers[] = 'Accept: */*';
$headers[] = 'Sec-Fetch-Site: same-origin';
$headers[] = 'Sec-Fetch-Mode: cors';
$headers[] = 'Sec-Fetch-Dest: empty';
$headers[] = 'Referer: https://yandex.ru/drive/podpiska/';
$headers[] = 'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

try {
    $result = json_decode($result, true, 512, JSON_THROW_ON_ERROR);
} catch (JsonException $e) {
    var_dump($e);
}

// Create Telegram API object
try {
    $telegram = new Longman\TelegramBot\Telegram($_ENV['BOT_TOKEN'], $_ENV['BOT_USERNAME']);
} catch (TelegramException $e) {
    var_dump($e);
}


$text = '';
foreach ($result['offers'] as $key => $value) {
    $text .= '🚗 '.$value['name'].' '.$value['subname'].PHP_EOL;
}

$ttt = Request::sendMessage([
    'chat_id' => $_ENV['BOT_CHAT_ID'],
    'text'    => $text
]);